name: 'CI'

on: [workflow_dispatch]

jobs:
  packer:
    name: 'Packer'
    runs-on: ubuntu-latest
    container:
      image: hashicorp/packer:latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - name: Packer Version
      run: packer --version

    - name: Check path
      run: pwd
    
    - name: Packer Validation
      run: packer validate -syntax-only ./packer/image.json

    - name: Packer execute jobs
      run: packer build ./packer/image.json
      env:
        ECR_AWS_ACCESS_KEY: ${{ secret.ECR_AWS_ACCESS_KEY}}
        ECR_AWS_SECRET_KEY: ${{ secret.ECR_AWS_SECRET_KEY}}
